#!/usr/bin/perl
# Copyright (c) 2013 Mitchell Cooper
# don't expect this to be pretty because it's just for testing

use warnings;
use strict;
use lib 'lib';

use Wikifier::Server;

# read the configuration page.
die "Please provide the configuration file as the first argument\n" unless @ARGV;
(my $conf = Wikifier::Page->new(file => shift @ARGV))->parse or die "Configuration error\n";

# create a loop.
my $loop = IO::Async::Loop->new;

my $stream;
$loop->connect(
    addr => {
        family   => 'unix',
        socktype => 'stream',
        path     => $conf->get('server.socket.path')
    },
    on_stream => sub {
        $stream = shift;
        print "Connected to $stream\n";
        $stream->configure(
            on_read => sub {
               my (undef, $buffref, $eof ) = @_;
               while( $$buffref =~ s/^(.*\n)// ) {
                  print "-> $1";
               }
                die "EOF\n" if $eof;
            }
        );
        $loop->add($stream);
    },
    on_connect_error => sub { die "connection error\n" }
);

$loop->add(IO::Async::Stream->new(
    read_handle => \*STDIN,
    on_read     => sub {
       my (undef, $buffref, $eof) = @_;
       while( $$buffref =~ s/^(.*\n)// ) {
          return unless $stream;
          print "<- $1";
          $stream->write($1);
       }
    }
));

$loop->run
