#!/usr/bin/perl
# Copyright (c) 2016, Mitchell Cooper
#
# This executable takes a filename as an argument,
# printing the parser's resulting output to STDOUT.
#
use warnings;
use strict;
use lib 'lib';

use Wikifier;
use Wikifier::Utilities qw(L);

my $path = shift @ARGV;
die "Need page file path" if !length $path;
die "Page does not exist" if !-e $path;

# create the page object.
my $page = Wikifier::Page->new(file_path => $path);

# parse the page.
my $err = $page->parse;
die $err if $err;

# print warnings.
L "Warning: $_" for @{ $page->{warnings} };

# print the generated HTML.
my ($html, $css) = ($page->html, $page->css);
L "CSS: $css" if length $css;
print $html if length $html;
