#!/usr/bin/perl
# Copyright (c) 2013 Mitchell Cooper

use warnings;
use strict;
use lib 'lib';

use Wikifier::Server;

# read the configuration page.
die "Please provide the configuration file as the first argument\n" unless @ARGV;
(my $conf = Wikifier::Page->new(file => shift @ARGV))->parse or die "Configuration error\n";

# create a loop.
$loop = IO::Async::Loop->new;

# start the server.
Wikifier::Server::start($loop, $conf);
