#!/usr/bin/perl
# Copyright (c) 2013, Mitchell Cooper
#
# This executable takes a filename as an argument,
# printing the parser's resulting output to STDOUT.
#

use warnings;
use strict;
use lib 'lib';

use Wikifier;

# image sizer.
sub image_sizer {
    my %opts = @_;
    my ($file, $width, $height) = ($opts{file}, $opts{width}, $opts{height});
    
    # notroll.net image sizer takes no 'auto' argument; just leave them out.
    $width  = $width  eq 'auto' ? '' : $width;
    $height = $height eq 'auto' ? '' : $height;
    
    # return the full URL of the image.
    return "http://images.notroll.net/paranoia/files/$file?height=$height&amp;width=$width";
}

# global wiki variables.
my %wiki_variables = (
    stats => {
        library => {
            books => '151,785,778'
        }
    }
);

# create the page object.
my $page = Wikifier::Page->new(
    file => shift @ARGV,
    wiki => {
        name            => 'NoTrollPlzNet Library',
        wiki_address    => '',
        image_directory => '/home/www/main/paranoia/files',
        image_address   => 'http://images.notroll.net/paranoia/files',
        variables       => \%wiki_variables,
        size_images     => 'server',
        image_sizer     => \&image_sizer,
        external_root   => 'http://en.wikipedia.org/wiki',
        rounding        => 'up'
    }
);

# parse the page.
$page->parse();

# print the generated HTML.
print $page->html();

