#!/usr/bin/perl
# Copyright (c) 2013, Mitchell Cooper
#
# This executable takes a filename as an argument,
# printing the parser's resulting output to STDOUT.
#

use warnings;
use strict;
use lib 'lib';

use Wikifier;

my $wikifier = Wikifier->new(file => shift @ARGV);
$wikifier->parse();

foreach (@{$wikifier->{main_block}{content}}) {
    print "content: $_\n";
}

$wikifier->{main_block}->result();

use Data::Dumper;
$Data::Dumper::Maxdepth = 5;
#print Dumper $wikifier->{main_block};
