#!/usr/bin/perl
#
# Copyright (c) 2013 Mitchell Cooper
#

use warnings;
use strict;
use lib 'lib';

use Wikifier::Server;

# read the configuration page.
die "Please provide the configuration file as the first argument\n" unless @ARGV;

# create a loop.
my $loop = IO::Async::Loop->new;

# start the server.
Wikifier::Server::start($loop, shift @ARGV);
